data:
  file_path: D:\WORK\freelance\agnet\dataset\face_kaggle.csv
  image_base_path: D:\WORK\freelance\agnet
  target_fields:
    - age
  batch_size: 2
  workers: 2
  n_splits: 1
  train_size: 0.8
  random_state: 7
  image_size: 768
  scale_factor: 10
  output_dim: 1

model: 
  name: AGNet
  # resnet50, resnet34, efficientnet_b5
  base_model: resnet50
  description: age and gender classification neural network
  lr: 0.001
  fp: fp32
  model_version: age_estimation_resnet34
  epochs: 128
  tqdm_enable: true
  output_dim: 1