data:
  file_path: D:\WORK\freelance\agnet\dataset\gender.csv
  image_base_path: D:\WORK\freelance\agnet
  target_fields:
    - gender
  batch_size: 2
  workers: 2
  n_splits: 1
  train_size: 0.8
  random_state: 7
  image_size: 456
  scale_factor: 10
  output_dim: 1
  fp: fp32

model: 
  name: AGNet
  # resnet50, resnet34, efficientnet_b5
  # for efficientnet_b5 image_size should be 456
  _base_model: efficientnet_b5
  transfer_learning: false
  mlp_layer_name: classifier # fc or classifier
  description: age and gender classification neural network
  lr: 0.001
  fp: fp32
  model_version: gender_estimation_resnet34
  epochs: 128
  tqdm_enable: true
  output_dim: 1
  model_save_path: ./